a=input("Enter the first  number:")
a=float(a)
b=input("Enter the second number:")
b=float(b)
c=(a+b)
d=(a*b)
e=(a-b)
f=(a/b)
print("Addition:",c)
print("Multiplication:",d)
print("Subtraction:",e)
print("Division:",f)
